name: passaqui
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cpf_cnpj_validator: ^2.0.0
  search_cep: ^4.0.2
  webview_flutter: ^4.8.0
  permission_handler: ^8.1.4


  http: ^1.2.1
  shared_preferences: ^2.0.6
  mask_text_input_formatter: ^2.0.0
  url_launcher: ^6.1.7
  intl: ^0.19.0

  get_it: ^7.7.0
  flutter_svg: ^2.0.10+1

  firebase_core: ^2.30.1
  firebase_crashlytics: ^3.5.4
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/withdraw/
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 500
        - asset: assets/fonts/Raleway-Thin.ttf
          weight: 400
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 600
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700